### ISSUE TITLE
how to use this code for multi_class classification?

### ISSUE THREAD

**Issue by mrmrn** [Theo-/sentiment-analysis-keras-conv#2]
hi, thank you for the code and the blog post.
how can I use this code for multi_class classification?

**Comment by Theo-** [comment]
Hi,

You would just need to modify L32:

```
model.add(Dense(1,activation='sigmoid'))
```

into

```
model.add(Dense(n,activation='sigmoid'))
```

where `n` is the number of classes that you have.

Of course you also need to modify your training data to match the format. (Y_text and Y_train must be an array of 1-hot vectors).

**Comment by mrmrn** [comment]
thank you for fast response.
could you please give me a link for creating that kind of  `array of 1-hot vectors`

**Comment by Theo-** [comment]
I believe this link can be useful: https://jovianlin.io/keras-one-hot-encode-decode-sequence-data/
